version: "3.9"

services:
  ingestion-service:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../ingestion-service:/app
    command: ["node", "server.js"]
    ports:
      - "3000:3000"
